current_version = "2024.12.12"

[[files]]
path = "pyproject.toml"

search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "src/atsphinx/toybox/__init__.py"

search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = ".github/release-body.md"
search = "Release atsphinx-toybox v{{ current_version }}"
replace = "Release atsphinx-toybox v{{ new_version }}"

[[files]]
path = ".github/release-body.md"
search = "- Changelog is https://github.com/atsphinx/toybox/blob/v{{ current_version }}/CHANGES.rst"
replace = "- Changelog is https://github.com/atsphinx/toybox/blob/v{{ new_version }}/CHANGES.rst"
